### ISSUE TITLE
Query regrading scale of individual modality likelihood

### ISSUE THREAD

**Issue by vandana-rajan** [iffsid/mmvae#3]
Hi,

Thanks for sharing the code. 

This is not an issue, rather a query.
I was wondering how did you come up with the scale of individual modality likelihood? (e.g; 0.75 for MNIST). Also, how do I decide that scale for a new dataset?

Thanks,

**Comment by YugeTen** [comment]
Hi, I would recommend doing a hypterparameters grid search for new dataset. We didn't do much fine tuning for the scaling term of the likelihood scale, and it does not seem to be overly crucial as long as it is within a sensible range.

**Comment by vandana-rajan** [comment]
I see. Thanks for the clarification Yuge.
