### ISSUE TITLE
Where is the cub.vocab ?

### ISSUE THREAD

**Issue by maogewudi007** [iffsid/mmvae#5]
Hi, I can't find  cub.vocab of  Caltech-UCSD Birds (CUB) dataset. Can you upload the file? Thanks!

**Comment by YugeTen** [comment]
Hi, 

When you run `main.py` with `--model cub`, the `cub.vocab` file should be automatically generated. See details here: https://github.com/iffsid/mmvae/blob/33e3c8ca23fc5ee3b461a6eef622cffc4ba7dc70/src/datasets.py#L143
