### ISSUE TITLE
Number of IWAE samples used for training

### ISSUE THREAD

**Issue by ry85** [iffsid/mmvae#6]
Thanks for sharing the code. Can you please tell me how many IWAE samples did you used for training the model. 

Also did you tried training the model with the vanilla iwae estimator? If yes, then can you please share what likelihoods did you get from it and from the DREG estimator.

Thanks a lot.

**Comment by iffsid** [comment]
The number of samples for the dreg estimator are given in the readme---its the value of `--K` in the arguments for the pre-trained models.

We did not train the model with the vanilla IWAE estimator, except at some very early prototyping stage. Don't have the values for that I'm afraid.
