### ISSUE TITLE
"ft"

### ISSUE THREAD

**Issue by jlian2** [iffsid/mmvae#8]
what is the difference between "mmvae_cub_images_sentences_ft" and "mmvae_cub_images_sentences"

**Comment by YugeTen** [comment]
`mmvae_cub_images_sentences_ft` is the model we reported in our paper, performing reconstruction of the feature of the images; `mmvae_cub_images_sentences` is a model we provide that reconstruct the raw images of CUB.

Kindly please read through the `README.md` before opening an issue.

Many thanks, 
Yuge
